"""
AI Scientist V2 — BFTS Configuration Management
Dataclass, preset profiles, and YAML generation for Best-First Tree Search config.
"""

import json
import logging
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


@dataclass
class BFTSConfig:
    """Configuration for AI-Scientist V2 Best-First Tree Search."""

    # Tree search parameters
    num_workers: int = 3
    steps: int = 5
    max_debug_depth: int = 3
    debug_prob: float = 0.5

    # Execution limits
    exec_timeout: int = 3600  # seconds per experiment node
    total_timeout: int = 7200  # seconds for entire BFTS run

    # Model assignments (V2 uses multi-model)
    model_code: str = "anthropic.claude-sonnet-4-20250514"
    model_feedback: str = "gpt-4o"
    model_writeup: str = "o1-preview"

    # Writeup
    include_writeup: bool = False
    writeup_format: str = "4page"  # "4page" (ICBINB) or "8page"
    citation_rounds: int = 2

    # Budget
    budget_usd: float = 30.0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_yaml_str(self) -> str:
        """Generate YAML config string for bfts_config.yaml."""
        lines = [
            "# AI-Scientist V2 BFTS Configuration (auto-generated by OSSR)",
            "",
            "# Tree search",
            f"num_workers: {self.num_workers}",
            f"steps: {self.steps}",
            f"max_debug_depth: {self.max_debug_depth}",
            f"debug_prob: {self.debug_prob}",
            "",
            "# Execution limits",
            f"exec_timeout: {self.exec_timeout}",
            f"total_timeout: {self.total_timeout}",
            "",
            "# Models",
            f"model_code: {self.model_code}",
            f"model_feedback: {self.model_feedback}",
            f"model_writeup: {self.model_writeup}",
            "",
            "# Writeup",
            f"include_writeup: {str(self.include_writeup).lower()}",
            f"writeup_format: {self.writeup_format}",
            f"citation_rounds: {self.citation_rounds}",
            "",
            "# Budget",
            f"budget_usd: {self.budget_usd}",
        ]
        return "\n".join(lines) + "\n"

    def write_yaml(self, directory: Path) -> Path:
        """Write bfts_config.yaml to directory. Returns path to written file."""
        directory.mkdir(parents=True, exist_ok=True)
        config_path = directory / "bfts_config.yaml"
        config_path.write_text(self.to_yaml_str(), encoding="utf-8")
        logger.info("[BFTSConfig] Wrote config to %s", config_path)
        return config_path

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "BFTSConfig":
        """Create from dict, ignoring unknown keys."""
        known = {f.name for f in cls.__dataclass_fields__.values()}
        filtered = {k: v for k, v in data.items() if k in known}
        return cls(**filtered)


# ── Preset Profiles ──────────────────────────────────────────────────

BFTS_PROFILES: Dict[str, BFTSConfig] = {
    "quick": BFTSConfig(
        num_workers=2,
        steps=3,
        max_debug_depth=2,
        debug_prob=0.3,
        exec_timeout=1800,
        total_timeout=3600,
        budget_usd=12.0,
        include_writeup=False,
    ),
    "standard": BFTSConfig(
        num_workers=3,
        steps=5,
        max_debug_depth=3,
        debug_prob=0.5,
        exec_timeout=3600,
        total_timeout=7200,
        budget_usd=30.0,
        include_writeup=False,
    ),
    "thorough": BFTSConfig(
        num_workers=4,
        steps=10,
        max_debug_depth=4,
        debug_prob=0.6,
        exec_timeout=5400,
        total_timeout=14400,
        budget_usd=50.0,
        include_writeup=True,
        writeup_format="8page",
        citation_rounds=3,
    ),
}


def resolve_bfts_config(
    profile: str = "standard",
    overrides: Optional[Dict[str, Any]] = None,
) -> BFTSConfig:
    """
    Resolve a BFTSConfig from a named profile with optional overrides.

    Args:
        profile: One of 'quick', 'standard', 'thorough'.
        overrides: Dict of field overrides (e.g. {'num_workers': 5}).

    Returns:
        Fully resolved BFTSConfig.
    """
    base = BFTS_PROFILES.get(profile)
    if base is None:
        logger.warning("[BFTSConfig] Unknown profile '%s', falling back to standard", profile)
        base = BFTS_PROFILES["standard"]

    if not overrides:
        return base

    merged = {**base.to_dict(), **overrides}
    return BFTSConfig.from_dict(merged)
